# unique project identifier
sonar.projectKey=MycWoodSort

# project name shown in SonarQube
sonar.projectName=MycWoodSort

# authentication token
sonar.token=sqp_42b849efb39f7747c81b4993b5910723dc050af3

# local SonarQube server
sonar.host.url=http://localhost:9000

# source and test folders
sonar.sources=src/main/scala
sonar.tests=src/test/scala

# encoding
sonar.sourceEncoding=UTF-8

# Scala coverage report
sonar.scala.coverage.reportPaths=target/scala-3.8.2/scoverage-report/scoverage.xml